/*
 * generated by Xtext 2.12.0
 */
package com.github.jucovschi

import org.eclipse.xtext.scoping.impl.DefaultGlobalScopeProvider

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class OCMRuntimeModule extends AbstractOCMRuntimeModule {
	override bindIGlobalScopeProvider() {
		DefaultGlobalScopeProvider
	}
}
