/*
 * generated by Xtext 2.12.0
 */
package com.github.jucovschi.ide

import com.github.jucovschi.OCMRuntimeModule
import com.github.jucovschi.OCMStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class OCMIdeSetup extends OCMStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new OCMRuntimeModule, new OCMIdeModule))
	}
	
}
